# Generated by Django 4.0.4 on 2024-06-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_image_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='note',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
